name: Run Atomic Red Team tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Atomic Red Team image
        run: |
          docker build -f Dockerfiles/Atomic-Red-Team-Install.dockerfile -t atomic-red-team .
      - name: Start Atomic Red Team container
        run: |
          docker run -d --name atomic-red-team atomic-red-team
      - name: Run Atomic Red Team tests
        run: |
          docker exec atomic-red-teamm powershell -Command 'invoke-atomic T1003.001'
      - name: Stop Atomic Red Team container
        run: |
          docker stop atomic-red-team
      - name: Remove Atomic Red Team container
        run: |
          docker rm atomic-red-team
