name: Run Atomic Red Team tests

on: [push]

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Hello World via Powershell
        run: |
          powershell.exe Write-Host "Hello World"
