name: Run Atomic Red Team tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Atomic Red Team image
        run: |
          docker build -t Dockerfiles/Atomic-Red-Team-Install.dockerfile .
      - name: Start Atomic Red Team container
        run: |
          docker run -d --name Atomic-Red-Team Atomic-Red-Team
      - name: Run Atomic Red Team tests
        run: |
          docker exec Atomic-Red-Team powershell -Command 'invoke-atomic T1003.001'
      - name: Stop Atomic Red Team container
        run: |
          docker stop Atomic-Red-Team
      - name: Remove Atomic Red Team container
        run: |
          docker rm Atomic-Red-Team
